apiVersion: v1
kind: Service
metadata:
  name: bakehouse-app-service
  namespace: app
spec:
  selector:
    app: bakehouse-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 30000 # 
