---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop -v /var/run/docker.sock:/var/run/docker.sock bakehouse-app
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm -v /var/run/docker.sock:/var/run/docker.sock bakehouse-app
      ignore_errors: yes

    - name: remove used image
      command: docker rmi -v /var/run/docker.sock:/var/run/docker.sock  0xze/bakehouse-app:latest
      ignore_errors: yes

    - name: build docker image from Dockerfile
      command: docker build -v /var/run/docker.sock:/var/run/docker.sock  -t 0xze/bakehouse-app:latest ../app

    - name: push image to dockerhub
      command: docker push -v /var/run/docker.sock:/var/run/docker.sock  0xze/bakehouse-app:latest
